server:
  port: 9091

access:
  username: lucas123
  password: lucas
  
management:
  endpoints:
    web:
      exposure:
        include:  health,info,refresh
  endpoint:
    refresh:
      enabled: true
