server:
  port: 9091

access:
  username: lucas123
  password: "{cipher}424f0cca5c867a8f64b785308373ee0bd22e0e019b4814dcafb2c6a1bf1568ee"
  
management:
  endpoints:
    web:
      exposure:
        include:  health,info,refresh
  endpoint:
    refresh:
      enabled: true
